# This is a config for PPIO Sandbox template
# You can use template ID (7xvs3snis3tkuq3y8u96) or template name (browser-chromium) to create a sandbox:

# Python SDK
# from ppio_sandbox.core import Sandbox, AsyncSandbox
# sandbox = Sandbox("browser-chromium") # Sync sandbox
# sandbox = await AsyncSandbox.create("browser-chromium") # Async sandbox

# JS SDK
# import { Sandbox } from 'ppio-sandbox'
# const sandbox = await Sandbox.create('browser-chromium')

template_id = "7xvs3snis3tkuq3y8u96"
dockerfile = "ppio.Dockerfile"
template_name = "browser-chromium"
start_cmd = "/app/.browser-use/start-up.sh"
team_id = "2e32c55b-3f42-4de2-868c-f5ddde123f5c"
